name: 🐛 Bug Report
description: Report a bug or unexpected behavior in MonitorX
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report

        Thank you for taking the time to report a bug! Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checks
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this bug hasn't been reported
          required: true
        - label: I am using the latest version of MonitorX
          required: true
        - label: I have read the documentation
          required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is
      placeholder: "When I do X, Y happens instead of Z..."
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the issue
      placeholder: |
        1. Start MonitorX with '...'
        2. Send a metric using '...'
        3. Check the dashboard at '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "The metric should be displayed in the dashboard..."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Instead, I get an error message: ..."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: MonitorX Version
      description: Which version are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: Which Python version are you using?
      placeholder: "3.9.7"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: Which OS are you running?
      placeholder: "Ubuntu 22.04 / macOS 13.0 / Windows 11"
    validations:
      required: true

  - type: dropdown
    id: deployment
    attributes:
      label: Deployment Method
      description: How are you running MonitorX?
      options:
        - Docker Compose
        - Manual Installation
        - Kubernetes
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Please paste any relevant log output
      placeholder: |
        Paste logs here...
      render: shell

  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Relevant configuration (remove sensitive information!)
      placeholder: |
        # .env contents (redact secrets!)
        INFLUXDB_URL=http://localhost:8086
        ...
      render: shell

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: "This started happening after upgrading from..."

  - type: checkboxes
    id: component
    attributes:
      label: Affected Components
      description: Which components are affected? (select all that apply)
      options:
        - label: API Server
        - label: Python SDK
        - label: Dashboard
        - label: Alerting
        - label: InfluxDB Integration
        - label: Documentation
        - label: Docker/Deployment
